services:

  # generate_key_alice_bob_client:
  #   build: ./keys
  #   container_name: generate_key_alice_bob_client
  #   environment:
  #     - BUFFER_SIZE=100000  # Key buffer size
  #     - BUFFER_PATH=/dev/shm/qkd_buffer_ab  # Key buffer memory path
  #     - MODE=sender  # Sender or receiver mode (Alice or Bob)
  #     - HOST=10.0.0.5  # Receiver host address
  #     - PORT=34560  # Receiver host port
  #     - SKR=100  # Secret Key Rate (in bytes per second)
  #   volumes:
  #     - qkd_shared_alice:/dev/shm

  qkd_server_alice:
    build: ./server
    container_name: qkd_server_alice
    environment:
      - SERVER_PORT=25575
      - LINK_BUFFER_MAP_FILE=/etc/qkd/link_map.json
      - LOCAL_NODE_UUID=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
    volumes:
      # - qkd_shared_alice:/dev/shm
      - /home/xilinx/jupyter_notebooks/cv-qkd/data:/dev/shm
      - ./config/link_map.json:/etc/qkd/link_map.json:ro
    network_mode: "host"
    restart: unless-stopped

volumes:
  qkd_shared_alice:
    driver_opts:
      type: tmpfs
      device: tmpfs
