services:
  qkd_server_bob:
    build: ./server
    container_name: qkd_server_bob
    environment:
      - SERVER_PORT=25576
    volumes:
      - qkd_shared_bob:/dev/shm
    ports:
      - "25575:25575"
    networks:
      - qkd_network

  generate_key_bob:
    build: ./keys
    container_name: generate_key_bob
    environment:
      - BUFFER_SIZE=100000  # Key buffer size
      - BUFFER_PATH=/dev/shm/qkd_buffer  # Key buffer memory path
      - MODE=receiver  # Sender or receiver mode (Alice or Bob)
      - PORT=5000  # Receiver host port
      - SKR=100  # Secret Key Rate (in bytes per second)
    volumes:
      - qkd_shared_bob:/dev/shm
    networks:
      key_network:
        ipv4_address: 10.0.0.20
    ports:
      - "5000:5000"

networks:
  qkd_network:
    driver: bridge
  key_network:
    driver: ipvlan
    driver_opts:
      parent: eno8303
    ipam:
      config:
        - subnet: 10.0.0.0/24
        
volumes:
  qkd_shared_bob:
    driver_opts:
      type: tmpfs
      device: tmpfs
